apiVersion : apps/v1
kind: Deployment
metadata:
  name: javav2 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javav2
  template:
    metadata:
      labels:
        app: javav2 
    spec:
      containers:
        - name: javav2 
          image: akspocregistrymbu2.azurecr.io/javav2
          ports:
          - containerPort: 8080