apiVersion : apps/v1
kind: Deployment
metadata:
  name: javav1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javav1
  template:
    metadata:
      labels:
        app: javav1 
    spec:
      containers:
        - name: javav1 
          image: akspocregistrymbu2.azurecr.io/javav1
          ports:
          - containerPort: 8080